
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="easy_villagers"
    type="optional"
    mandatory=false
    versionRange="[1.1.15,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="trade_cycling"
    type="optional"
    mandatory=false
    versionRange="[1.21.1-1.0.0,)"  # Adjust version range as needed
    ordering="AFTER"
    side="BOTH"
